print('hello world')
print('您好')

print('  *  ')
print(' *** ')
print('*****')
print('-------------------')
print('|     欢迎登录     |')
print('-------------------')
print('|   >>>1.登录>>>   |')
print('|   >>>2.注册>>>   |')
print('|   >>>0.退出>>>   |')
print('-------------------')